### ISSUE TITLE
Mod Name Conflict (1.12.2)

### ISSUE THREAD

**Issue by Collecter128** [CoffeeCatRailway/CheeseMod#2]
I think your mod has a conflict problem with another mod with a similar name. https://www.curseforge.com/minecraft/mc-mods/cheesemod-nuclearbanana
It's a shame, because I think both mods are awesome. I hope there is a fix for this.

**Comment by CoffeeCatRailway** [comment]
I'm not updating 1.12 anymore and I'm using the id in 1.14 but if you choose to update to 1.13 or up you could use something like "nbcheesemod" so that they don't conflict anymore...?

**Comment by Collecter128** [comment]
?
 I'm not the mod author so I don't know how to do that. 
I think they are updating to 1.14 soon, so you might be able to talk to them before they do.
