### ISSUE TITLE
Leaves does not show solid blocks behind them

### ISSUE THREAD

**Issue by TelepathicGrunt** [CoffeeCatRailway/CheeseMod#3]
Leaves with CoffeeCatsCheeseMod will allow x-ray to happen like so:
![image](https://user-images.githubusercontent.com/40846040/81456606-f4501b80-9160-11ea-81a0-d8de4aab1c08.png)

This is because the leaves property need to have .notSolid() called here in order for MC to know to render blocks behind the leaves:
https://github.com/CoffeeCatRailway/CoffeeCatsCheeseMod/blob/006bacb75cf485ea44e329ef3329e34eccf83956/src/main/java/coffeecatrailway/coffeecheese/registry/ModBlocks.java#L141

I hope this helps!

**Comment by CoffeeCatRailway** [comment]
Thank you!
I can't believe I missid this, I've been trying to fix this for so long XD
